In [1]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)




[[1 2 3]
 [4 5 6]]


In [2]:
b=np.array([1,2,3],ndmin=5)
print(b)
np.ndim(b)

[[[[[1 2 3]]]]]


5

In [3]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.eye(3)
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
a.shape
a.dtype
a.itemsize
np.arange(0,10,1)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.random.randint(0,10,(2,3))

array([[6, 7, 6],
       [4, 0, 4]], dtype=int32)

In [8]:
b=np.random.randint(0,10,(3,3))
print(b)
b[0][1]

[[4 5 6]
 [8 5 8]
 [5 1 7]]


np.int32(5)

In [9]:
a[a>3]

array([], dtype=float64)

In [10]:
a=np.array([1,2,3])
b=np.array([7,8,9])
print(a+b)
print(a-b)
print(a>b)

[ 8 10 12]
[-6 -6 -6]
[False False False]


In [11]:
np.mean(a)

np.float64(2.0)

In [12]:
np.median(a)

np.float64(2.0)

In [13]:
np.std(a)

np.float64(0.816496580927726)

In [14]:
np.var(a)

np.float64(0.6666666666666666)

In [15]:
np.percentile(a,15)

np.float64(1.3)

In [16]:
np.max(a)

np.int64(3)

In [17]:
np.min(a)

np.int64(1)

In [18]:
np.argmin(a)

np.int64(0)

In [19]:
np.sum(a)

np.int64(6)

In [20]:
np.prod(a)

np.int64(6)

In [21]:
np.corrcoef(a)

np.float64(1.0)

In [22]:
np.average(5)

np.float64(5.0)

In [23]:
np.sort(a)

array([1, 2, 3])

In [24]:
np.argsort(a)

array([0, 1, 2])

In [25]:
np.add(a,b)

array([ 8, 10, 12])

In [26]:
np.subtract(a,b)

array([-6, -6, -6])

In [27]:
np.pow(a,b)

array([    1,   256, 19683])

In [28]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [29]:
np.log(b)

array([1.94591015, 2.07944154, 2.19722458])

In [30]:
np.greater(a,b)

array([False, False, False])

In [31]:
np.maximum(a,b)

array([7, 8, 9])

In [32]:
np.minimum(a,b)

array([1, 2, 3])

In [33]:
np.fmax(a,b)

array([7, 8, 9])

In [34]:
np.fmin(a,b)

array([1, 2, 3])

In [35]:
a.dot(a)

np.int64(14)

In [36]:
a@b

np.int64(50)

In [37]:
a.T

array([1, 2, 3])

In [38]:
np.transpose(a)

array([1, 2, 3])

In [39]:
c=np.array([[1,2],[3,4],[5,6]])
c.T

array([[1, 3, 5],
       [2, 4, 6]])

In [40]:
d=c.reshape(3,2)
print(d)

[[1 2]
 [3 4]
 [5 6]]
