In [1]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)




[[1 2 3]
 [4 5 6]]


In [2]:
b=np.array([1,2,3],ndmin=5)
print(b)
np.ndim(b)

[[[[[1 2 3]]]]]


5

In [3]:
np.ones((2,3))


array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.eye(3)
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
a.shape
a.dtype
a.itemsize
np.arange(0,10,1)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.random.randint(0,10,(2,3))


array([[5, 1, 3],
       [8, 0, 6]], dtype=int32)

In [7]:
b=np.random.randint(0,10,(3,3))
print(b)
b[0][1]

[[6 3 1]
 [8 9 3]
 [9 1 1]]


np.int32(3)

In [8]:
a[a>3]

array([], dtype=float64)

In [9]:
a=np.array([1,2,3])
b=np.array([7,8,9])
print(a+b)
print(a-b)
print(a>b)

[ 8 10 12]
[-6 -6 -6]
[False False False]


In [10]:
np.mean(a)

np.float64(2.0)

In [11]:
np.median(a)

np.float64(2.0)

In [12]:
np.std(a)

np.float64(0.816496580927726)

In [13]:
np.var(a)

np.float64(0.6666666666666666)

In [14]:
np.percentile(a,15)

np.float64(1.3)

In [15]:
np.max(a)

np.int64(3)

In [16]:
np.min(a)

np.int64(1)

In [17]:
np.argmin(a)

np.int64(0)

In [18]:
np.sum(a)

np.int64(6)

In [19]:
np.prod(a)

np.int64(6)

In [20]:
np.corrcoef(a)

np.float64(1.0)

In [21]:
np.average(5)

np.float64(5.0)

In [22]:
np.sort(a)

array([1, 2, 3])

In [23]:
np.argsort(a)

array([0, 1, 2])

In [24]:
np.add(a,b)

array([ 8, 10, 12])

In [25]:
np.subtract(a,b)

array([-6, -6, -6])

In [26]:
np.pow(a,b)

array([    1,   256, 19683])

In [27]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [28]:
np.log(b)

array([1.94591015, 2.07944154, 2.19722458])

In [29]:
np.greater(a,b)


array([False, False, False])

In [30]:
np.maximum(a,b)

array([7, 8, 9])

In [31]:
np.minimum(a,b)

array([1, 2, 3])

In [32]:
np.fmax(a,b)

array([7, 8, 9])

In [33]:
np.fmin(a,b)

array([1, 2, 3])

In [34]:
a.dot(a)

np.int64(14)

In [35]:
a@b

np.int64(50)

In [36]:
a.T

array([1, 2, 3])

In [37]:
np.transpose(a)

array([1, 2, 3])

In [38]:
c=np.array([[1,2],[3,4],[5,6]])
c.T

array([[1, 3, 5],
       [2, 4, 6]])

In [39]:
d=c.reshape(3,2)
print(d)

[[1 2]
 [3 4]
 [5 6]]


In [40]:
pip install pandas


Note: you may need to restart the kernel to use updated packages.


In [41]:
import pandas as pd
df=pd.read_csv("Area_Population_Density_and_Population_2011_Census.csv")
df.head


<bound method NDFrame.head of           District  Geograpical Area (Sq.Kms)  Population Density      Male  \
0         Chikkodi                        851                 419    181619   
1           Athani                       1554                 240    190310   
2           Raibag                        952                 426    207142   
3            Gokak                       1146                 348    200104   
4          Hukkeri                        987                 405    200490   
..             ...                        ...                 ...       ...   
223       Shorapur                       1014                 249    126942   
224  Gurumithakala                        697                 206     71320   
225       Vadagera                        704                 156     55044   
226       Hunisigi                        826                 194     81231   
227    State Total                     191791                 319  30966657   

       Female     Tot

In [42]:
df.tail()

District  Geograpical Area (Sq.Kms)  Population Density      Male  \
223       Shorapur                       1014                 249    126942   
224  Gurumithakala                        697                 206     71320   
225       Vadagera                        704                 156     55044   
226       Hunisigi                        826                 194     81231   
227    State Total                     191791                 319  30966657   

       Female     Total  Percentage Share to Total Population  Rank  
223    125391    252333                                  21.0   3.0  
224     71942    143262                                  12.0   5.0  
225     54708    109752                                   9.0   3.0  
226     78727    159958                                  14.0   4.0  
227  30128640  61095297                                 100.0   NaN

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 228 entries, 0 to 227
Data columns (total 8 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   District                              228 non-null    object 
 1   Geograpical Area (Sq.Kms)             228 non-null    int64  
 2   Population Density                    228 non-null    int64  
 3   Male                                  228 non-null    int64  
 4   Female                                228 non-null    int64  
 5    Total                                228 non-null    int64  
 6   Percentage Share to Total Population  228 non-null    float64
 7   Rank                                  227 non-null    float64
dtypes: float64(2), int64(5), object(1)
memory usage: 14.4+ KB


In [44]:
df.shape

(228, 8)

In [45]:
df.describe()

Geograpical Area (Sq.Kms)  Population Density          Male  \
count                 228.000000          228.000000  2.280000e+02   
mean                 1682.377193          326.399123  2.716373e+05   
std                 12652.081507          378.260607  2.050760e+06   
min                   123.000000           28.000000  1.803000e+04   
25%                   538.500000          186.000000  6.679200e+04   
50%                   797.500000          249.000000  1.027085e+05   
75%                  1064.500000          352.500000  1.437400e+05   
max                191791.000000         5082.000000  3.096666e+07   

             Female         Total  Percentage Share to Total Population  \
count  2.280000e+02  2.280000e+02                            228.000000   
mean   2.642863e+05  5.359237e+05                             13.594474   
std    1.994551e+06  4.045298e+06                             10.277710   
min    1.756500e+04  3.564400e+04                              1.930000   
25%    6.818700e+04  1.343270e+05                              7.435000   
50%    1.022780e+05  2.064120e+05                             10.440000   
75%    1.416150e+05  2.848725e+05                             17.185000   
max    3.012864e+07  6.109530e+07                            100.000000   

             Rank  
count  227.000000  
mean     4.612335  
std      2.865638  
min      1.000000  
25%      2.000000  
50%      4.000000  
75%      6.000000  
max     14.000000

In [46]:
df.columns

Index(['District', 'Geograpical Area (Sq.Kms)', 'Population Density', 'Male',
       'Female', ' Total', 'Percentage Share to Total Population', 'Rank'],
      dtype='object')

In [47]:
df.dtypes

District                                 object
Geograpical Area (Sq.Kms)                 int64
Population Density                        int64
Male                                      int64
Female                                    int64
 Total                                    int64
Percentage Share to Total Population    float64
Rank                                    float64
dtype: object

In [48]:
10000*8

80000

In [49]:
df[" Total"]=df[" Total"].astype("float32")


In [50]:
df.loc[2:10]

District  Geograpical Area (Sq.Kms)  Population Density    Male  Female  \
2       Raibag                        952                 426  207142  198347   
3        Gokak                       1146                 348  200104  198288   
4      Hukkeri                        987                 405  200490  198780   
5     Belagavi                       1032                 928  486704  470669   
6     Khanapur                       1742                 148  130598  127491   
7    Savadatti                       1578                 224  178755  174174   
8   Bailhongal                        760                 380  145681  143187   
9     Ramadurg                       1225                 211  130910  127617   
10    Kitthuru                        360                 256   46781   45540   

       Total  Percentage Share to Total Population  Rank  
2   405489.0                                  8.48   2.0  
3   398392.0                                  8.34   4.0  
4   399270.0                                  8.35   3.0  
5   957373.0                                 20.03   1.0  
6   258089.0                                  5.40  11.0  
7   352929.0                                  7.38   7.0  
8   288868.0                                  6.04   9.0  
9   258527.0                                  5.41  10.0  
10   92321.0                                  1.93  14.0

In [51]:
df.loc[2:10,[" Total","Rank"]]

Total  Rank
2   405489.0   2.0
3   398392.0   4.0
4   399270.0   3.0
5   957373.0   1.0
6   258089.0  11.0
7   352929.0   7.0
8   288868.0   9.0
9   258527.0  10.0
10   92321.0  14.0

In [52]:
df.iloc[2:10,[2,3]]

Population Density    Male
2                 426  207142
3                 348  200104
4                 405  200490
5                 928  486704
6                 148  130598
7                 224  178755
8                 380  145681
9                 211  130910

In [53]:
df.iloc[0:51,[2,4,5,3]]

Population Density  Female     Total    Male
0                  419  174525  356144.0  181619
1                  240  182265  372575.0  190310
2                  426  198347  405489.0  207142
3                  348  198288  398392.0  200104
4                  405  198780  399270.0  200490
5                  928  470669  957373.0  486704
6                  148  127491  258089.0  130598
7                  224  174174  352929.0  178755
8                  380  143187  288868.0  145681
9                  211  127617  258527.0  130910
10                 256   45540   92321.0   46781
11                 662  134478  272656.0  138178
12                 351   74988  153257.0   78269
13                 538  106249  213771.0  107522
14                 307  131380  263971.0  132591
15                 206   80147  160294.0   80147
16                 287  125194  250193.0  124999
17                 227  119544  241415.0  121871
18                 307  141894  285114.0  143220
19                 218   75981  153209.0   77228
20                 275   44568   89445.0   44877
21                 258   83616  168129.0   84513
22                 732  137317  277982.0  140665
23                 489  229570  466644.0  237074
24                 195  144611  299458.0  154847
25                 196  134121  276236.0  142115
26                 165   84126  170705.0   86579
27                 194   89025  179332.0   90307
28                 231   43027   87138.0   44111
29                 155   63747  128909.0   65162
30                 176   58895  121711.0   62816
31                 182   65625  132152.0   66527
32                 146   60579  125522.0   64943
33                 185   40074   81588.0   41514
34                 150   52909  107936.0   55027
35                 198  152409  314301.0  161892
36                 168  107282  220339.0  113057
37                 589  361616  737387.0  375771
38                 168  104204  209843.0  105639
39                 213  109974  218572.0  108598
40                 226  121155  242987.0  121832
41                 166   88475  179100.0   90625
42                 153   55324  110034.0   54710
43                 183   62738  128183.0   65445
44                 155   57533  117803.0   60270
45                 411   43861   87777.0   43916
46                 309  149953  306619.0  156666
47                 248  135747  277350.0  141603
48                 228   84669  173047.0   88378
49                 507  228846  469941.0  241095
50                 314   98458  201293.0  102835

In [54]:
df[df["Rank"]>11]


District  Geograpical Area (Sq.Kms)  Population Density    Male  Female  \
10  Kitthuru                        360                 256   46781   45540   
12  Kagavada                        437                 351   78269   74988   
13  Mudalagi                        397                 538  107522  106249   
33   Kolhara                        277                 185   41514   40074   
84     Joida                       1882                  28   26167   25845   

       Total  Percentage Share to Total Population  Rank  
10   92321.0                                  1.93  14.0  
12  153257.0                                  3.21  13.0  
13  213771.0                                  4.47  12.0  
33   81588.0                                  3.75  12.0  
84   52012.0                                  3.62  12.0

In [55]:
df[(df["Population Density"])&(df["Population Density"]>200)]


District  Geograpical Area (Sq.Kms)  Population Density      Male  \
0       Chikkodi                        851                 419    181619   
4        Hukkeri                        987                 405    200490   
9       Ramadurg                       1225                 211    130910   
12      Kagavada                        437                 351     78269   
14    Jamakhandi                        882                 307    132591   
..           ...                        ...                 ...       ...   
217       Magadi                        795                 257    102582   
219  Channapatna                        539                 485    130408   
222     Shahapur                       1002                 253    128414   
223     Shorapur                       1014                 249    126942   
227  State Total                     191791                 319  30966657   

       Female       Total  Percentage Share to Total Population  Rank  
0      174525    356144.0                                  7.45   6.0  
4      198780    399270.0                                  8.35   3.0  
9      127617    258527.0                                  5.41  10.0  
12      74988    153257.0                                  3.21  13.0  
14     131380    263971.0                                 13.97   3.0  
..        ...         ...                                   ...   ...  
217    101259    203841.0                                 18.83   4.0  
219    130896    261304.0                                 24.14   3.0  
222    125455    253869.0                                 22.00   1.0  
223    125391    252333.0                                 21.00   3.0  
227  30128640  61095296.0                                100.00   NaN  

[68 rows x 8 columns]

In [58]:
df.query("Rank>5")

District  Geograpical Area (Sq.Kms)  Population Density    Male  \
0             Chikkodi                        851                 419  181619   
6             Khanapur                       1742                 148  130598   
7            Savadatti                       1578                 224  178755   
8           Bailhongal                        760                 380  145681   
9             Ramadurg                       1225                 211  130910   
..                 ...                        ...                 ...     ...   
194             Kadaba                        722                 163   59867   
198        Piriyapatna                        812                 301  124755   
202  Heggadadevanakote                       1116                 171   90651   
205           Saraguru                        502                 149   42097   
213          Gudibande                        227                 246   28078   

     Female     Total  Percentage Share to Total Population  Rank  
0    174525  356144.0                                  7.45   6.0  
6    127491  258089.0                                  5.40  11.0  
7    174174  352929.0                                  7.38   7.0  
8    143187  288868.0                                  6.04   9.0  
9    127617  258527.0                                  5.41  10.0  
..      ...       ...                                   ...   ...  
194   60090  119957.0                                  5.70   6.0  
198  118321  243076.0                                  8.10   6.0  
202   88665  179316.0                                  5.97   7.0  
205   42293   84390.0                                  2.81   8.0  
213   27754   55832.0                                  4.45   6.0  

[78 rows x 8 columns]

In [59]:
df.query("Rank>5 and `Population Density`>200")

District  Geograpical Area (Sq.Kms)  Population Density    Male  \
0         Chikkodi                        851                 419  181619   
7        Savadatti                       1578                 224  178755   
8       Bailhongal                        760                 380  145681   
9         Ramadurg                       1225                 211  130910   
10        Kitthuru                        360                 256   46781   
11         Nippani                        412                 662  138178   
12        Kagavada                        437                 351   78269   
13        Mudalagi                        397                 538  107522   
15          Bilagi                        781                 206   80147   
19         Hungund                        733                 218   77228   
20     Guledagudda                        316                 275   44877   
21           Ilkal                        626                 258   84513   
28       Nidagundi                        399                 231   44111   
39           Sedam                       1021                 213  108598   
45       Shahbadha                        220                 411   43916   
57           Manvi                       1020                 231   89034   
68        Naragund                        436                 231   51276   
81        Alnavara                        123                 289   18079   
94        Dandelli                        293                 226   33387   
99         Byadagi                        433                 326   72143   
100      Hirekerur                        385                 312   61417   
102    Ratteehalli                        416                 267   56902   
103       Hadagali                        948                 206   98853   
110       Kurugodu                        470                 247   58159   
111        Kotturu                        253                 386   49626   
112         Kampli                        355                 345   60706   
125        Nyamati                        372                 258   46566   
136        Bynduru                        583                 214   58936   
152     Koratagere                        647                 259   84349   
155         Tiptur                        784                 284  111282   
156     Turuvekere                        781                 216   83950   
157        Kunigal                        981                 230  112803   
163          K.G.F                        378                 567  127489   
175     Pandavpura                        528                 347   92038   
176  Srirangapatna                        368                 490   89940   
181          Belur                        845                 219   91306   
193      Mudabidri                        294                 355   51722   
198    Piriyapatna                        812                 301  124755   
213      Gudibande                        227                 246   28078   

     Female     Total  Percentage Share to Total Population  Rank  
0    174525  356144.0                                  7.45   6.0  
7    174174  352929.0                                  7.38   7.0  
8    143187  288868.0                                  6.04   9.0  
9    127617  258527.0                                  5.41  10.0  
10    45540   92321.0                                  1.93  14.0  
11   134478  272656.0                                  5.70   8.0  
12    74988  153257.0                                  3.21  13.0  
13   106249  213771.0                                  4.47  12.0  
15    80147  160294.0                                  8.48   7.0  
19    75981  153209.0                                  8.11   8.0  
20    44568   89445.0                                  4.73   9.0  
21    83616  168129.0                                  8.90   6.0  
28    43027   87138.0                        

In [ ]:
df.query("Rank>5 and `Population Density`>200")

In [65]:
df.query("Rank>10 and `Population Density`>300")
df

District  Geograpical Area (Sq.Kms)  Population Density      Male  \
0         Chikkodi                        851                 419    181619   
1           Athani                       1554                 240    190310   
2           Raibag                        952                 426    207142   
3            Gokak                       1146                 348    200104   
4          Hukkeri                        987                 405    200490   
..             ...                        ...                 ...       ...   
223       Shorapur                       1014                 249    126942   
224  Gurumithakala                        697                 206     71320   
225       Vadagera                        704                 156     55044   
226       Hunisigi                        826                 194     81231   
227    State Total                     191791                 319  30966657   

       Female       Total  Percentage Share to Total Population  Rank  mRank  \
0      174525    356144.0                                  7.45   6.0   60.0   
1      182265    372575.0                                  7.80   5.0   50.0   
2      198347    405489.0                                  8.48   2.0   20.0   
3      198288    398392.0                                  8.34   4.0   40.0   
4      198780    399270.0                                  8.35   3.0   30.0   
..        ...         ...                                   ...   ...    ...   
223    125391    252333.0                                 21.00   3.0   30.0   
224     71942    143262.0                                 12.00   5.0   50.0   
225     54708    109752.0                                  9.00   3.0   30.0   
226     78727    159958.0                                 14.00   4.0   40.0   
227  30128640  61095296.0                                100.00   NaN    NaN   

                   test  
0            [Chikkodi]  
1             [Ath, ni]  
2            [R, ib, g]  
3              [Gok, k]  
4             [Hukkeri]  
..                  ...  
223         [Shor, pur]  
224  [Gurumith, k, l, ]  
225       [V, d, ger, ]  
226          [Hunisigi]  
227     [St, te Tot, l]  

[228 rows x 10 columns]

In [61]:
df["mRank"]=df["Rank"]*10
df

District  Geograpical Area (Sq.Kms)  Population Density      Male  \
0         Chikkodi                        851                 419    181619   
1           Athani                       1554                 240    190310   
2           Raibag                        952                 426    207142   
3            Gokak                       1146                 348    200104   
4          Hukkeri                        987                 405    200490   
..             ...                        ...                 ...       ...   
223       Shorapur                       1014                 249    126942   
224  Gurumithakala                        697                 206     71320   
225       Vadagera                        704                 156     55044   
226       Hunisigi                        826                 194     81231   
227    State Total                     191791                 319  30966657   

       Female       Total  Percentage Share to Total Population  Rank  mRank  
0      174525    356144.0                                  7.45   6.0   60.0  
1      182265    372575.0                                  7.80   5.0   50.0  
2      198347    405489.0                                  8.48   2.0   20.0  
3      198288    398392.0                                  8.34   4.0   40.0  
4      198780    399270.0                                  8.35   3.0   30.0  
..        ...         ...                                   ...   ...    ...  
223    125391    252333.0                                 21.00   3.0   30.0  
224     71942    143262.0                                 12.00   5.0   50.0  
225     54708    109752.0                                  9.00   3.0   30.0  
226     78727    159958.0                                 14.00   4.0   40.0  
227  30128640  61095296.0                                100.00   NaN    NaN  

[228 rows x 9 columns]

In [64]:
df["test"]=df["District"].str.split("a")
df

District  Geograpical Area (Sq.Kms)  Population Density      Male  \
0         Chikkodi                        851                 419    181619   
1           Athani                       1554                 240    190310   
2           Raibag                        952                 426    207142   
3            Gokak                       1146                 348    200104   
4          Hukkeri                        987                 405    200490   
..             ...                        ...                 ...       ...   
223       Shorapur                       1014                 249    126942   
224  Gurumithakala                        697                 206     71320   
225       Vadagera                        704                 156     55044   
226       Hunisigi                        826                 194     81231   
227    State Total                     191791                 319  30966657   

       Female       Total  Percentage Share to Total Population  Rank  mRank  \
0      174525    356144.0                                  7.45   6.0   60.0   
1      182265    372575.0                                  7.80   5.0   50.0   
2      198347    405489.0                                  8.48   2.0   20.0   
3      198288    398392.0                                  8.34   4.0   40.0   
4      198780    399270.0                                  8.35   3.0   30.0   
..        ...         ...                                   ...   ...    ...   
223    125391    252333.0                                 21.00   3.0   30.0   
224     71942    143262.0                                 12.00   5.0   50.0   
225     54708    109752.0                                  9.00   3.0   30.0   
226     78727    159958.0                                 14.00   4.0   40.0   
227  30128640  61095296.0                                100.00   NaN    NaN   

                   test  
0            [Chikkodi]  
1             [Ath, ni]  
2            [R, ib, g]  
3              [Gok, k]  
4             [Hukkeri]  
..                  ...  
223         [Shor, pur]  
224  [Gurumith, k, l, ]  
225       [V, d, ger, ]  
226          [Hunisigi]  
227     [St, te Tot, l]  

[228 rows x 10 columns]

In [67]:
df[(df["Rank"]>10)&(df["Population Density"]>300)]


District  Geograpical Area (Sq.Kms)  Population Density    Male  Female  \
12    Kagavada                        437                 351   78269   74988   
13    Mudalagi                        397                 538  107522  106249   
45   Shahbadha                        220                 411   43916   43861   
111    Kotturu                        253                 386   49626   47802   

        Total  Percentage Share to Total Population  Rank  mRank  \
12   153257.0                                  3.21  13.0  130.0   
13   213771.0                                  4.47  12.0  120.0   
45    87777.0                                  3.42  11.0  110.0   
111   97428.0                                  4.00  11.0  110.0   

               test  
12   [K, g, v, d, ]  
13     [Mud, l, gi]  
45   [Sh, hb, dh, ]  
111       [Kotturu]

In [68]:
df.query("Rank>10 and `Population Density`>300")

District  Geograpical Area (Sq.Kms)  Population Density    Male  Female  \
12    Kagavada                        437                 351   78269   74988   
13    Mudalagi                        397                 538  107522  106249   
45   Shahbadha                        220                 411   43916   43861   
111    Kotturu                        253                 386   49626   47802   

        Total  Percentage Share to Total Population  Rank  mRank  \
12   153257.0                                  3.21  13.0  130.0   
13   213771.0                                  4.47  12.0  120.0   
45    87777.0                                  3.42  11.0  110.0   
111   97428.0                                  4.00  11.0  110.0   

               test  
12   [K, g, v, d, ]  
13     [Mud, l, gi]  
45   [Sh, hb, dh, ]  
111       [Kotturu]

In [69]:
df.isnull()

District  Geograpical Area (Sq.Kms)  Population Density   Male  Female  \
0       False                      False               False  False   False   
1       False                      False               False  False   False   
2       False                      False               False  False   False   
3       False                      False               False  False   False   
4       False                      False               False  False   False   
..        ...                        ...                 ...    ...     ...   
223     False                      False               False  False   False   
224     False                      False               False  False   False   
225     False                      False               False  False   False   
226     False                      False               False  False   False   
227     False                      False               False  False   False   

      Total  Percentage Share to Total Population   Rank  mRank   test  
0     False                                 False  False  False  False  
1     False                                 False  False  False  False  
2     False                                 False  False  False  False  
3     False                                 False  False  False  False  
4     False                                 False  False  False  False  
..      ...                                   ...    ...    ...    ...  
223   False                                 False  False  False  False  
224   False                                 False  False  False  False  
225   False                                 False  False  False  False  
226   False                                 False  False  False  False  
227   False                                 False   True   True  False  

[228 rows x 10 columns]

In [71]:
df.isnull().sum()

District                                0
Geograpical Area (Sq.Kms)               0
Population Density                      0
Male                                    0
Female                                  0
 Total                                  0
Percentage Share to Total Population    0
Rank                                    1
mRank                                   1
test                                    0
dtype: int64

In [72]:
df.drop("test",axis=1)

District  Geograpical Area (Sq.Kms)  Population Density      Male  \
0         Chikkodi                        851                 419    181619   
1           Athani                       1554                 240    190310   
2           Raibag                        952                 426    207142   
3            Gokak                       1146                 348    200104   
4          Hukkeri                        987                 405    200490   
..             ...                        ...                 ...       ...   
223       Shorapur                       1014                 249    126942   
224  Gurumithakala                        697                 206     71320   
225       Vadagera                        704                 156     55044   
226       Hunisigi                        826                 194     81231   
227    State Total                     191791                 319  30966657   

       Female       Total  Percentage Share to Total Population  Rank  mRank  
0      174525    356144.0                                  7.45   6.0   60.0  
1      182265    372575.0                                  7.80   5.0   50.0  
2      198347    405489.0                                  8.48   2.0   20.0  
3      198288    398392.0                                  8.34   4.0   40.0  
4      198780    399270.0                                  8.35   3.0   30.0  
..        ...         ...                                   ...   ...    ...  
223    125391    252333.0                                 21.00   3.0   30.0  
224     71942    143262.0                                 12.00   5.0   50.0  
225     54708    109752.0                                  9.00   3.0   30.0  
226     78727    159958.0                                 14.00   4.0   40.0  
227  30128640  61095296.0                                100.00   NaN    NaN  

[228 rows x 9 columns]

In [73]:
df

District  Geograpical Area (Sq.Kms)  Population Density      Male  \
0         Chikkodi                        851                 419    181619   
1           Athani                       1554                 240    190310   
2           Raibag                        952                 426    207142   
3            Gokak                       1146                 348    200104   
4          Hukkeri                        987                 405    200490   
..             ...                        ...                 ...       ...   
223       Shorapur                       1014                 249    126942   
224  Gurumithakala                        697                 206     71320   
225       Vadagera                        704                 156     55044   
226       Hunisigi                        826                 194     81231   
227    State Total                     191791                 319  30966657   

       Female       Total  Percentage Share to Total Population  Rank  mRank  \
0      174525    356144.0                                  7.45   6.0   60.0   
1      182265    372575.0                                  7.80   5.0   50.0   
2      198347    405489.0                                  8.48   2.0   20.0   
3      198288    398392.0                                  8.34   4.0   40.0   
4      198780    399270.0                                  8.35   3.0   30.0   
..        ...         ...                                   ...   ...    ...   
223    125391    252333.0                                 21.00   3.0   30.0   
224     71942    143262.0                                 12.00   5.0   50.0   
225     54708    109752.0                                  9.00   3.0   30.0   
226     78727    159958.0                                 14.00   4.0   40.0   
227  30128640  61095296.0                                100.00   NaN    NaN   

                   test  
0            [Chikkodi]  
1             [Ath, ni]  
2            [R, ib, g]  
3              [Gok, k]  
4             [Hukkeri]  
..                  ...  
223         [Shor, pur]  
224  [Gurumith, k, l, ]  
225       [V, d, ger, ]  
226          [Hunisigi]  
227     [St, te Tot, l]  

[228 rows x 10 columns]

In [80]:
df.drop(2,axis=0,inplace=True)
df

District  Geograpical Area (Sq.Kms)  Population Density      Male  \
0         Chikkodi                        851                 419    181619   
1           Athani                       1554                 240    190310   
3            Gokak                       1146                 348    200104   
4          Hukkeri                        987                 405    200490   
5         Belagavi                       1032                 928    486704   
..             ...                        ...                 ...       ...   
223       Shorapur                       1014                 249    126942   
224  Gurumithakala                        697                 206     71320   
225       Vadagera                        704                 156     55044   
226       Hunisigi                        826                 194     81231   
227    State Total                     191791                 319  30966657   

       Female       Total  Percentage Share to Total Population  mRank  
0      174525    356144.0                                  7.45   60.0  
1      182265    372575.0                                  7.80   50.0  
3      198288    398392.0                                  8.34   40.0  
4      198780    399270.0                                  8.35   30.0  
5      470669    957373.0                                 20.03   10.0  
..        ...         ...                                   ...    ...  
223    125391    252333.0                                 21.00   30.0  
224     71942    143262.0                                 12.00   50.0  
225     54708    109752.0                                  9.00   30.0  
226     78727    159958.0                                 14.00   40.0  
227  30128640  61095296.0                                100.00    NaN  

[227 rows x 8 columns]

In [77]:
df

District  Geograpical Area (Sq.Kms)  Population Density      Male  \
0         Chikkodi                        851                 419    181619   
1           Athani                       1554                 240    190310   
2           Raibag                        952                 426    207142   
3            Gokak                       1146                 348    200104   
4          Hukkeri                        987                 405    200490   
..             ...                        ...                 ...       ...   
223       Shorapur                       1014                 249    126942   
224  Gurumithakala                        697                 206     71320   
225       Vadagera                        704                 156     55044   
226       Hunisigi                        826                 194     81231   
227    State Total                     191791                 319  30966657   

       Female       Total  Percentage Share to Total Population  Rank  mRank  
0      174525    356144.0                                  7.45   6.0   60.0  
1      182265    372575.0                                  7.80   5.0   50.0  
2      198347    405489.0                                  8.48   2.0   20.0  
3      198288    398392.0                                  8.34   4.0   40.0  
4      198780    399270.0                                  8.35   3.0   30.0  
..        ...         ...                                   ...   ...    ...  
223    125391    252333.0                                 21.00   3.0   30.0  
224     71942    143262.0                                 12.00   5.0   50.0  
225     54708    109752.0                                  9.00   3.0   30.0  
226     78727    159958.0                                 14.00   4.0   40.0  
227  30128640  61095296.0                                100.00   NaN    NaN  

[228 rows x 9 columns]

In [82]:
df.loc[0:227,"mRank"]

0      60.0
1      50.0
3      40.0
4      30.0
5      10.0
       ... 
223    30.0
224    50.0
225    30.0
226    40.0
227     NaN
Name: mRank, Length: 227, dtype: float64

In [87]:
df.loc[50:150,"mRank"]

50     20.0
51     20.0
52     20.0
53     10.0
54     30.0
       ... 
146    40.0
147    50.0
148    40.0
149    20.0
150    60.0
Name: mRank, Length: 101, dtype: float64

In [90]:
df.fillna(5,axis=0,inplace=True)
df

District  Geograpical Area (Sq.Kms)  Population Density      Male  \
0         Chikkodi                        851                 419    181619   
1           Athani                       1554                 240    190310   
3            Gokak                       1146                 348    200104   
4          Hukkeri                        987                 405    200490   
5         Belagavi                       1032                 928    486704   
..             ...                        ...                 ...       ...   
223       Shorapur                       1014                 249    126942   
224  Gurumithakala                        697                 206     71320   
225       Vadagera                        704                 156     55044   
226       Hunisigi                        826                 194     81231   
227    State Total                     191791                 319  30966657   

       Female       Total  Percentage Share to Total Population  mRank  
0      174525    356144.0                                  7.45   60.0  
1      182265    372575.0                                  7.80   50.0  
3      198288    398392.0                                  8.34   40.0  
4      198780    399270.0                                  8.35   30.0  
5      470669    957373.0                                 20.03   10.0  
..        ...         ...                                   ...    ...  
223    125391    252333.0                                 21.00   30.0  
224     71942    143262.0                                 12.00   50.0  
225     54708    109752.0                                  9.00   30.0  
226     78727    159958.0                                 14.00   40.0  
227  30128640  61095296.0                                100.00    5.0  

[227 rows x 8 columns]

In [91]:
df.ffill(axis=0)

District  Geograpical Area (Sq.Kms)  Population Density      Male  \
0         Chikkodi                        851                 419    181619   
1           Athani                       1554                 240    190310   
3            Gokak                       1146                 348    200104   
4          Hukkeri                        987                 405    200490   
5         Belagavi                       1032                 928    486704   
..             ...                        ...                 ...       ...   
223       Shorapur                       1014                 249    126942   
224  Gurumithakala                        697                 206     71320   
225       Vadagera                        704                 156     55044   
226       Hunisigi                        826                 194     81231   
227    State Total                     191791                 319  30966657   

       Female       Total  Percentage Share to Total Population  mRank  
0      174525    356144.0                                  7.45   60.0  
1      182265    372575.0                                  7.80   50.0  
3      198288    398392.0                                  8.34   40.0  
4      198780    399270.0                                  8.35   30.0  
5      470669    957373.0                                 20.03   10.0  
..        ...         ...                                   ...    ...  
223    125391    252333.0                                 21.00   30.0  
224     71942    143262.0                                 12.00   50.0  
225     54708    109752.0                                  9.00   30.0  
226     78727    159958.0                                 14.00   40.0  
227  30128640  61095296.0                                100.00    5.0  

[227 rows x 8 columns]

In [92]:
df.bfill(axis=0)

District  Geograpical Area (Sq.Kms)  Population Density      Male  \
0         Chikkodi                        851                 419    181619   
1           Athani                       1554                 240    190310   
3            Gokak                       1146                 348    200104   
4          Hukkeri                        987                 405    200490   
5         Belagavi                       1032                 928    486704   
..             ...                        ...                 ...       ...   
223       Shorapur                       1014                 249    126942   
224  Gurumithakala                        697                 206     71320   
225       Vadagera                        704                 156     55044   
226       Hunisigi                        826                 194     81231   
227    State Total                     191791                 319  30966657   

       Female       Total  Percentage Share to Total Population  mRank  
0      174525    356144.0                                  7.45   60.0  
1      182265    372575.0                                  7.80   50.0  
3      198288    398392.0                                  8.34   40.0  
4      198780    399270.0                                  8.35   30.0  
5      470669    957373.0                                 20.03   10.0  
..        ...         ...                                   ...    ...  
223    125391    252333.0                                 21.00   30.0  
224     71942    143262.0                                 12.00   50.0  
225     54708    109752.0                                  9.00   30.0  
226     78727    159958.0                                 14.00   40.0  
227  30128640  61095296.0                                100.00    5.0  

[227 rows x 8 columns]

In [93]:
df.drop_duplicates()

District  Geograpical Area (Sq.Kms)  Population Density      Male  \
0         Chikkodi                        851                 419    181619   
1           Athani                       1554                 240    190310   
3            Gokak                       1146                 348    200104   
4          Hukkeri                        987                 405    200490   
5         Belagavi                       1032                 928    486704   
..             ...                        ...                 ...       ...   
223       Shorapur                       1014                 249    126942   
224  Gurumithakala                        697                 206     71320   
225       Vadagera                        704                 156     55044   
226       Hunisigi                        826                 194     81231   
227    State Total                     191791                 319  30966657   

       Female       Total  Percentage Share to Total Population  mRank  
0      174525    356144.0                                  7.45   60.0  
1      182265    372575.0                                  7.80   50.0  
3      198288    398392.0                                  8.34   40.0  
4      198780    399270.0                                  8.35   30.0  
5      470669    957373.0                                 20.03   10.0  
..        ...         ...                                   ...    ...  
223    125391    252333.0                                 21.00   30.0  
224     71942    143262.0                                 12.00   50.0  
225     54708    109752.0                                  9.00   30.0  
226     78727    159958.0                                 14.00   40.0  
227  30128640  61095296.0                                100.00    5.0  

[227 rows x 8 columns]

In [2]:
import pandas as pd
#df=pd.read_csv("Area_Population_Density_and_Population_2011_Census.csv")
#df.head


In [3]:
users = pd.DataFrame({
    'user_id': [1,2,3,4],
    'user_type': ['Free','Premium','Free','Premium']
})
activity=pd.DataFrame({
    'user_id':[1,2,1,3,4,2,4],
    'login_count':[5,15,7,8,10,20,15],
    'rating':[3.5,4.2,3.9,4.0,4.8,4.5,4.7]
})    

In [8]:
activity.groupby("user_id").agg({
    "login_count":"sum",
    "rating":"mean",
})

login_count  rating
user_id                     
1                 12    3.70
2                 35    4.35
3                  8    4.00
4                 25    4.75

In [9]:
activity.merge(users,on="user_id")

user_id  login_count  rating user_type
0        1            5     3.5      Free
1        2           15     4.2   Premium
2        1            7     3.9      Free
3        3            8     4.0      Free
4        4           10     4.8   Premium
5        2           20     4.5   Premium
6        4           15     4.7   Premium

In [ ]:
pd.merge(users,activity,on="user_id")

user_id user_type  login_count  rating
0        1      Free            5     3.5
1        1      Free            7     3.9
2        2   Premium           15     4.2
3        2   Premium           20     4.5
4        3      Free            8     4.0
5        4   Premium           10     4.8
6        4   Premium           15     4.7

In [12]:
pd.merge(users,activity,on="user_id",how="inner")

user_id user_type  login_count  rating
0        1      Free            5     3.5
1        1      Free            7     3.9
2        2   Premium           15     4.2
3        2   Premium           20     4.5
4        3      Free            8     4.0
5        4   Premium           10     4.8
6        4   Premium           15     4.7

In [13]:
df1=pd.DataFrame({
    'user_id':[1,2,3],
    'name':['Alice','Bob','Charlie']
})
df2=pd.DataFrame({
    'user_id':[2,3,4],
    'age':[25,30,22]
})
merged_df=pd.merge(df1,df2,on='user_id',how='inner')
merged_df

user_id     name  age
0        2      Bob   25
1        3  Charlie   30

In [18]:
df1=pd.DataFrame({
    'user_id':[1,2,3],
    'name':['Alice','Bob','Charlie']
})
df2=pd.DataFrame({
    'user_id':[2,3,4],
    'age':[25,30,22]
})
merged_df=pd.merge(df1,df2,on='user_id',how='outer')
merged_df

user_id     name   age
0        1    Alice   NaN
1        2      Bob  25.0
2        3  Charlie  30.0
3        4      NaN  22.0

In [23]:
f1=pd.DataFrame({
    
    'name':['Alice','Bob','Charlie']
})
df2=pd.DataFrame({
    
    'age':[25,30,22]
})
df1.join(df2,how="left")

user_id     name  age
0        1    Alice   25
1        2      Bob   30
2        3  Charlie   22

In [24]:
df1.to_csv("data.csv")

In [26]:
pip install matplotlib

  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 762.0 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/8.1 MB 958.5 kB/s eta 0:00:08
   ------ --------------------------------- 1.3/8.1 MB 1.4 MB/s eta 0:00:05
   --------- ------------------------------ 1.8/8.1 MB 1.5 MB/s eta 0:00:05
   ---------- ----------------------------- 2.1/8.1 MB 1.6 MB/s eta 0:00:04
   ---------- ----------------------------- 2.1/8.1 MB 1.6 MB/s eta 0:00:04
   ---------- ----------------------------- 2.1/8.1 MB 1.6 MB/s eta 0:00:04
   ---------- ----------------------------- 2.1/8.1 MB 1.6 MB/s eta 0:00:04
   ---------- ----------------------------- 2.1/8.1 MB 1.6 MB/s eta 0:00:04
   ---------- ---------------------------